dataset:
  train_dir: data/train
  val_dir: data/val
  test_dir: data/test

train:
  gpus: null
  early_stop: false
  run_test: false
  batch_size: 512
  max_epochs: 1000
  n_data_workers: 4
  train_percent: 1.0
  val_percent: 1.0
